services:
  ubuntu-dev:
    build: .
    container_name: ubuntu
    volumes:
      - .:/workspace
    # Keep the container running so we can exec into it
    tty: true
    stdin_open: true
    # Working directory when entering the container
    working_dir: /workspace
